BASIC:
  GPU: [0,]
  DATA_PATH: './dataset/root'
  CHECKPOINT: './checkpoint'
  OVERWRITE: False
  WORKERS: 15
  VOCAB_SIZE: 400
  EMBEDDING_SIZE: 256
  FRAMES: 64

TRAIN:
  EPOCHS: 200
  BATCH_SIZE: 128
  LR: 1e-5
  RESUME: True
  TENSORBOARD: './tensorboard'

INFERENCE:
  PRODUCTION: True

